import type { OrderAlert } from '../common/OrderAlertBanner'

export const SHIPPING_ALERTS: OrderAlert[] = [
  {
    id: 'ship-1',
    type: 'shipment-pickup-delay',
    title: '揽收延迟提醒',
    message: '运单 DO00065124 已超过承运商约定揽收时间 6 小时仍未完成揽收。我们已联系承运商催促，预计今日内完成取件。',
    refId: 'DO00065124',
    severity: 'medium',
    actionLabel: '查看物流轨迹',
    actionPath: '/shipping/tracking',
  },
  {
    id: 'ship-2',
    type: 'tracking-anomaly',
    title: '运输轨迹异常',
    message: '运单 DO00065121 物流轨迹超过 24 小时无更新，且当前位置偏离预定路线。承运商正在核实情况，我们会持续跟踪。',
    refId: 'DO00065121',
    severity: 'high',
    actionLabel: '查看轨迹详情',
    actionPath: '/shipping/tracking',
    secondaryActionLabel: '联系客服',
    secondaryActionPath: '/support/requests/new',
  },
  {
    id: 'ship-3',
    type: 'delivery-delay',
    title: '派送延迟通知',
    message: '运单 DO00065320 末端派送超过约定时效仍未完成签收。承运商反馈因收件地址门禁限制暂未送达，将再次尝试派送。',
    refId: 'DO00065320',
    severity: 'medium',
    actionLabel: '查看派送状态',
    actionPath: '/shipping/tracking',
  },
  {
    id: 'ship-4',
    type: 'shipment-pickup-delay',
    title: '批量揽收延迟',
    message: '今日有 5 个运单因承运商车辆调度问题未能按时揽收，涉及 TECHCORE 客户订单。备选承运商已安排，预计延迟 4-6 小时。',
    refId: '5 shipments',
    severity: 'high',
    actionLabel: '查看受影响运单',
    actionPath: '/shipping/shipments',
    secondaryActionLabel: '申请加急',
    secondaryActionPath: '/support/requests/new?topic=expedite&priority=Critical',
  },
  {
    id: 'ship-5',
    type: 'delivery-delay',
    title: '极端天气配送延误',
    message: '受中西部暴风雪影响，12 个运单配送预计延误 1-2 个工作日。承运商已更新预计送达时间，受影响客户将收到邮件通知。',
    refId: '12 shipments',
    severity: 'medium',
    actionLabel: '查看受影响运单',
    actionPath: '/shipping/shipments',
  },
]
