import type { OrderAlert } from '../common/OrderAlertBanner'

export const OUTBOUND_ALERTS: OrderAlert[] = [
  {
    id: 'out-1',
    type: 'order-stuck',
    title: '订单处理卡滞',
    message: '您有 120 个订单在分拣环节滞留超过 4 小时，可能影响当日发货。我们正在优先处理，如需加急请提交请求。',
    refId: 'BATCH-240624-A',
    severity: 'high',
    actionLabel: '查看详情',
    actionPath: '/support/item/WI-011',
    secondaryActionLabel: '申请加急',
    secondaryActionPath: '/support/requests/new?topic=expedite&priority=Critical',
  },
  {
    id: 'out-2',
    type: 'order-overdue',
    title: '订单发货延误',
    message: '订单 ORD-20260622-9901 已超出承诺发货时间 36 小时，原因为承运商取件延误。我们已联系备选承运商，正在加紧处理。',
    refId: 'ORD-20260622-9901',
    severity: 'high',
    actionLabel: '查看处理进度',
    actionPath: '/support/item/WI-012',
  },
  {
    id: 'out-3',
    type: 'sla-risk',
    title: 'SLA 风险预警',
    message: '预计有 35 个订单将在 4 小时内达到 SLA 截止时间，当前处理进度落后。如不干预约 20 个订单可能超时。',
    refId: 'BATCH-SLA-240624',
    severity: 'high',
    actionLabel: '查看风险订单',
    actionPath: '/support/item/WI-015',
    secondaryActionLabel: '申请加急处理',
    secondaryActionPath: '/support/requests/new?topic=expedite&priority=Critical',
  },
  {
    id: 'out-4',
    type: 'address-exception',
    title: '地址异常暂停',
    message: '18 个订单因收货地址无法识别已暂停发货，请尽快核实地址信息。如需改派地址可直接提交请求。',
    refId: '18 orders',
    severity: 'medium',
    actionLabel: '查看异常订单',
    actionPath: '/support/item/WI-013',
  },
  {
    id: 'out-5',
    type: 'shipment-delayed',
    title: '运输延误通知',
    message: '包裹 SHP-20260622-0055 因极端天气在中转枢纽延误，预计额外延误 2 个工作日。承运商已确认后续配送计划。',
    refId: 'SHP-20260622-0055',
    severity: 'medium',
    actionLabel: '查看物流详情',
    actionPath: '/support/item/WI-016',
  },
  {
    id: 'out-sla-1',
    type: 'sla-risk',
    title: '仓库作业 SLA 风险',
    message: '当前有 8 个出库任务距离 SLA 截止时间不足 4 小时，涉及 TECHCORE 客户订单。仓库正在加紧处理，建议关注进度。',
    refId: '8 tasks',
    severity: 'high',
    actionLabel: '查看风险任务',
    actionPath: '/support/item/WI-015',
  },
]

export const INBOUND_ALERTS: OrderAlert[] = [
  {
    id: 'in-1',
    type: 'adjustment-approval',
    title: '收货差异待确认',
    message: '采购订单 PO-20260622-114 到货数量与 PO 不符：预计 100 件，实收 110 件。请确认是否接受超收部分。',
    refId: 'PO-20260622-114',
    severity: 'medium',
    actionLabel: '去确认',
    actionPath: '/support/item/WI-009',
  },
  {
    id: 'in-2',
    type: 'order-stuck',
    title: '到货提醒',
    message: '采购订单 PO-20260624-201 已完成收货入库，实收 2,400 件，与 PO 一致。所有 SKU 已上架，可立即出库。',
    refId: 'PO-20260624-201',
    severity: 'low',
    actionLabel: '查看收货详情',
    actionPath: '/inbound/receipt/RN-110210',
  },
  {
    id: 'in-3',
    type: 'sla-risk',
    title: '到货预报提醒',
    message: '您预计下周（6月30日-7月4日）有 20,000 件货物到达。仓库已收到预报并开始准备，请确认最终到货计划。',
    refId: 'FORECAST-W27',
    severity: 'medium',
    actionLabel: '查看备货计划',
    actionPath: '/support/item/WI-018',
  },
  {
    id: 'in-sla-1',
    type: 'sla-risk',
    title: '入库作业 SLA 提醒',
    message: '采购订单 PO-20260625-305 预计今日到达，收货作业需在 4 小时内完成。仓库已安排人员待命。',
    refId: 'PO-20260625-305',
    severity: 'medium',
    actionLabel: '查看收货安排',
    actionPath: '/support/item/WI-018',
  },
]
