import { createContext, useContext, useState, useCallback, ReactNode } from 'react'
import type {
  WorkItem, WorkItemStatus, WorkItemComment, WorkItemEvidence,
} from '../types/workItem'

// ─── Seed Data ────────────────────────────────────────────────────────────────
const SEED_ITEMS: WorkItem[] = [

  // ── 问题类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-001',
    type: 'Alert',
    driver: 'IssueDriven',
    scenario: 'suspected-damage',
    title: '疑似货物损坏 — SKU TCORE-X100 入库检查',
    description: 'AI 系统检测到 TechCore SKU TCORE-X100 在入库扫描时存在包装异常，30件外箱出现压损迹象。仓库需要您授权拍照检查，并确认后续处置方案。',
    source: 'Agent',
    isAgentGenerated: true,
    agentName: 'Inbound Inspector Agent',
    createdBy: 'system',
    assignee: 'inbound-team',
    owner: 'Inbound Team',
    status: 'Open',
    priority: 'High',
    isPriority: false,
    createdAt: '2026-06-24T08:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
    slaDeadline: '2026-06-24T20:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-X100',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['damage', 'inbound', 'photo-needed'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '入库异常检测，自动创建工单', actor: 'Inbound Inspector Agent', toStatus: 'Open', timestamp: '2026-06-24T08:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '申请拍照检查', description: '仓库为您拍摄损坏照片，留存证据', icon: 'Camera', serviceId: 'photo-request', variant: 'primary' },
      { id: 'r2', label: 'SKU 全量检查', description: '对该批次所有 SKU 进行专业质检', icon: 'Search', serviceId: 'sku-inspection', variant: 'secondary' },
      { id: 'r3', label: '发起处置申请', description: '选择销毁、退货、翻修或暂置', icon: 'Package', variant: 'warning' },
    ],
    scenarioData: {
      skuId: 'TCORE-X100',
      skuName: 'TechCore Pro Hub X100',
      totalQty: 500,
      damagedQty: 30,
      warehouseNote: '外箱均有明显压损，内部产品状态待确认，需拍照记录',
      photoCount: 0,
    },
  },

  {
    id: 'WI-002',
    type: 'Alert',
    driver: 'IssueDriven',
    scenario: 'inventory-buildup',
    title: '库存积压预警 — SKU FW-DENIM-001 滞销 180 天',
    description: 'Fashionwave SKU FW-DENIM-001 已在仓库存放 180 天无任何出库记录，当前库存 850 件，持续产生存储费用。建议尽快制定处置计划。',
    source: 'System',
    isAgentGenerated: true,
    agentName: 'Inventory Health Agent',
    createdBy: 'system',
    assignee: 'account-mgr',
    owner: 'Account Team',
    status: 'Open',
    priority: 'Medium',
    createdAt: '2026-06-20T09:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'FW-DENIM-001',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: true,
    estimatedFee: 1200,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['slow-moving', 'storage-cost', 'fashionwave'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '库存滞销 180 天自动触发警报', actor: 'Inventory Health Agent', toStatus: 'Open', timestamp: '2026-06-20T09:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '发起库存盘点', description: '核实实际库存数量与系统是否一致', icon: 'ClipboardList', serviceId: 'inventory-audit-service', variant: 'secondary' },
      { id: 'r2', label: '申请货物拍照', description: '确认库存现状，评估货物品质', icon: 'Camera', serviceId: 'photo-request', variant: 'secondary' },
      { id: 'r3', label: '申请处置销毁', description: '申请合规销毁，停止存储费用累积', icon: 'Trash2', serviceId: 'disposition-service', variant: 'warning' },
      { id: 'r4', label: '安排退货回仓', description: '将货物退回至您指定的地址', icon: 'RotateCcw', variant: 'secondary' },
    ],
    scenarioData: {
      skuId: 'FW-DENIM-001',
      systemReceived: 850,
      available: 850,
      damaged: 0,
      daysNoMovement: 180,
    } as import('../types/workItem').InventoryAnomalyData,
  },

  {
    id: 'WI-003',
    type: 'Alert',
    driver: 'IssueDriven',
    scenario: 'missing-item',
    title: '货物追踪请求 — SHP-20260620-0087 疑似丢货',
    description: '出库扫描记录显示货物 SHP-20260620-0087 已于 6月20日发出，但终端消费者反映至今未收到。已联系承运商 FedEx，正在调查中。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'shipping-ops',
    owner: 'Shipping Team',
    status: 'InProgress',
    priority: 'High',
    isPriority: true,
    createdAt: '2026-06-23T10:00:00Z',
    updatedAt: '2026-06-24T09:30:00Z',
    slaDeadline: '2026-06-26T17:00:00Z',
    relatedObjectType: 'Shipment',
    relatedObjectId: 'SHP-20260620-0087',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['missing', 'investigation', 'fedex'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'Lisa (TechCore)', role: 'Customer', content: '终端客户非常着急，请尽快查明去向', createdAt: '2026-06-23T10:30:00Z', isInternal: false },
      { id: 'c2', author: 'Sam (Shipping)', role: 'Warehouse', content: '已联系 FedEx 开启追踪调查，预计 48 小时回复', createdAt: '2026-06-23T14:00:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '客户发起丢货追踪请求', actor: 'TechCore Portal', toStatus: 'Open', timestamp: '2026-06-23T10:00:00Z' },
      { id: 'a2', action: '联系承运商开启调查', actor: 'Sam (Shipping)', fromStatus: 'Open', toStatus: 'InProgress', timestamp: '2026-06-23T14:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '查看实时追踪详情', description: '承运商最新扫描记录与位置信息', icon: 'MapPin', variant: 'primary' },
      { id: 'r2', label: '提交承运商理赔', description: '如确认丢失，启动保险理赔流程', icon: 'FileText', variant: 'secondary' },
    ],
  },

  {
    id: 'WI-004',
    type: 'Alert',
    driver: 'IssueDriven',
    scenario: 'frozen-inventory',
    title: '库存冻结通知 — SKU FW-2024-RED 300 件冻结',
    description: 'Fashionwave SKU FW-2024-RED 库存被系统标记为冻结状态，共 300 件。冻结原因：海关文件待补充。需要您尽快提供相关文件以解冻库存，避免影响出库。',
    source: 'System',
    isAgentGenerated: false,
    createdBy: 'customs-system',
    assignee: 'compliance-team',
    owner: 'Compliance Team',
    status: 'Open',
    priority: 'High',
    isPriority: true,
    createdAt: '2026-06-22T14:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
    slaDeadline: '2026-06-25T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'FW-2024-RED',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['frozen', 'customs', 'compliance'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '系统检测到库存冻结，自动通知客户', actor: 'Customs System', toStatus: 'Open', timestamp: '2026-06-22T14:00:00Z' },
    ],
    scenarioData: {
      skuId: 'FW-2024-RED',
      systemReceived: 300,
      available: 0,
      damaged: 0,
    } as import('../types/workItem').InventoryAnomalyData,
  },

  // ── 请求类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-005',
    type: 'Request',
    driver: 'RequestDriven',
    scenario: 'expedite-request',
    title: '加急处理请求 — ORD-20260624-5521 闪购截止 24 小时',
    description: 'TechCore 发起紧急加急请求，订单 ORD-20260624-5521 包含 120 件，需要在 6月25日 12:00 前完成出库。该订单与客户 Prime Day 促销活动绑定，延误将影响活动履约。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'outbound-team',
    owner: 'Outbound Team',
    status: 'Open',
    priority: 'Critical',
    isPriority: true,
    createdAt: '2026-06-24T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-25T12:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'ORD-20260624-5521',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 25,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['expedite', 'prime-day', 'urgent'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '客户发起加急请求', actor: 'TechCore Portal', toStatus: 'Open', timestamp: '2026-06-24T10:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '确认加急处理', description: '提升为最高优先级，当日完成出库', icon: 'Zap', serviceId: 'expedite-processing', variant: 'primary' },
      { id: 'r2', label: '升级快递服务', description: '升级为次日达，确保准时送达', icon: 'Truck', serviceId: 'upgrade-shipping', variant: 'secondary' },
    ],
  },

  {
    id: 'WI-006',
    type: 'Request',
    driver: 'RequestDriven',
    scenario: 'disposition-request',
    title: '货物处置申请 — TCORE-X100 20 件损坏待处置',
    description: '仓库盘点发现 TechCore SKU TCORE-X100 有 20 件损坏，已无法正常销售。请您选择处置方式：销毁、退货、翻修或暂置。不同方式对应不同费用和时间线，请根据您的业务需求选择。',
    source: 'Warehouse',
    isAgentGenerated: false,
    createdBy: 'warehouse-team',
    assignee: 'account-mgr',
    owner: 'Account Team',
    status: 'PendingApproval',
    priority: 'Medium',
    createdAt: '2026-06-23T09:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-X100',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 60,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['disposition', 'damage', 'decision-needed'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'Warehouse Team', role: 'Warehouse', content: '20 件确认为包装破损，内部产品亦有部分损伤，建议翻修或销毁', createdAt: '2026-06-23T09:30:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '仓库发起处置申请，等待客户决定', actor: 'Warehouse Team', toStatus: 'PendingApproval', timestamp: '2026-06-23T09:00:00Z' },
    ],
    scenarioData: {
      skuId: 'TCORE-X100',
      skuName: 'TechCore Pro Hub X100',
      damagedQty: 20,
      damageType: '包装挤压导致外观及功能损坏',
      warehouseNote: '建议优先考虑翻修，约 60% 可恢复可售状态',
      options: [
        { id: 'dispose', label: '销毁处置', description: '合规销毁，出具销毁证书', cost: '$30/批次', timeline: '3-5 个工作日', bestFor: '损坏严重无法修复，需要合规清账' },
        { id: 'return', label: '退货回仓', description: '返回至您指定的收货地址', cost: '$45（含运费）', timeline: '5-7 个工作日', bestFor: '需要自行处理或转移至其他仓库' },
        { id: 'rework', label: '翻修再售', description: '仓库工人修复包装，恢复可售状态', cost: '$2.50/件', timeline: '2-3 个工作日', bestFor: '产品本身完好，仅包装损坏' },
        { id: 'hold', label: '暂置保留', description: '原地保存，等待进一步决定', cost: '存储费照常计算', timeline: '即时生效', bestFor: '暂时不确定，需要更多时间评估' },
      ],
    } as import('../types/workItem').DispositionData,
  },

  {
    id: 'WI-007',
    type: 'Request',
    driver: 'RequestDriven',
    scenario: 'vas-fulfillment',
    title: 'Kitting 服务请求 — Prime Day 礼品套装 5,000 件',
    description: 'TechCore 申请为 Prime Day 促销活动制作 5,000 套礼品套装，每套包含：Hub X100 × 1、Type-C Cable × 2、Cleaning Kit × 1。要求 6月30日前完成。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'value-add-team',
    owner: 'Value-Add Services',
    status: 'InProgress',
    priority: 'High',
    createdAt: '2026-06-20T11:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    slaDeadline: '2026-06-30T17:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'VAS-20260620-K001',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 4000,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['kitting', 'prime-day', 'vas'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: 'Kitting 服务请求已受理', actor: 'Value-Add Team', toStatus: 'InProgress', timestamp: '2026-06-20T14:00:00Z' },
    ],
  },

  // ── 审批类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-008',
    type: 'Approval',
    driver: 'ApprovalDriven',
    scenario: 'cycle-count-approval',
    title: '库存盘点差异确认 — SKU TCORE-CABLE 系统 100 实盘 96',
    description: '仓库完成 SKU TCORE-CABLE 专项盘点。系统数量：100 件，实盘数量：96 件，差异：-4 件。差异可能原因：货物损坏丢弃或记录误差。请您审批库存调整，或选择继续调查。',
    source: 'Warehouse',
    isAgentGenerated: false,
    createdBy: 'warehouse-ops',
    assignee: 'techcore-portal',
    owner: 'Finance Team',
    status: 'PendingApproval',
    priority: 'Medium',
    isPriority: true,
    createdAt: '2026-06-23T16:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    slaDeadline: '2026-06-26T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-CABLE',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['cycle-count', 'approval', 'variance'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '仓库提交盘点结果，等待客户确认', actor: 'Warehouse Ops', toStatus: 'PendingApproval', timestamp: '2026-06-23T16:00:00Z' },
    ],
    scenarioData: {
      skuId: 'TCORE-CABLE',
      skuName: 'TechCore USB-C Cable (3-Pack)',
      systemQty: 100,
      physicalQty: 96,
      variance: -4,
      countDate: '2026-06-23',
      countedBy: 'James W. (Warehouse Lead)',
    } as import('../types/workItem').CycleCountData,
  },

  {
    id: 'WI-009',
    type: 'Approval',
    driver: 'ApprovalDriven',
    scenario: 'receiving-discrepancy',
    title: '收货差异确认 — PO-20260622-114 多收 10 件',
    description: '采购订单 PO-20260622-114 到货数量与 PO 不符：PO 数量 100 件，实收 110 件，超收 10 件。需要您决定：接受超收（按实收计费）、退回超收部分或暂置待确认。',
    source: 'System',
    isAgentGenerated: false,
    createdBy: 'inbound-system',
    assignee: 'techcore-portal',
    owner: 'Inbound Team',
    status: 'PendingApproval',
    priority: 'Medium',
    isPriority: true,
    createdAt: '2026-06-22T15:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-25T17:00:00Z',
    relatedObjectType: 'PO',
    relatedObjectId: 'PO-20260622-114',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 110,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['receiving', 'discrepancy', 'po-variance'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '收货完成，发现数量差异，等待客户确认', actor: 'Inbound System', toStatus: 'PendingApproval', timestamp: '2026-06-22T15:00:00Z' },
    ],
    scenarioData: {
      poId: 'PO-20260622-114',
      poQty: 100,
      receivedQty: 110,
      variance: 10,
      skuId: 'TCORE-X100',
      skuName: 'TechCore Pro Hub X100',
      receivedDate: '2026-06-22',
    } as import('../types/workItem').ReceivingDiscrepancyData,
  },

  {
    id: 'WI-010',
    type: 'Approval',
    driver: 'ApprovalDriven',
    scenario: 'cycle-count-approval',
    title: '全仓盘点结果确认 — SKU A 差异 +30 件库存异常',
    description: 'Portal 显示 SKU A 收货 1,000 件，当前可用 970 件，差异 30 件标记为损坏。仓库已完成损坏核查，请您审批库存调整方案并选择后续处置方式。',
    source: 'Warehouse',
    isAgentGenerated: false,
    createdBy: 'warehouse-ops',
    assignee: 'fashionwave-portal',
    owner: 'Operations Team',
    status: 'PendingApproval',
    priority: 'High',
    isPriority: true,
    createdAt: '2026-06-24T07:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-25T12:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'FW-SKU-A',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['inventory-anomaly', 'damage', 'approval'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'Warehouse Team', role: 'Warehouse', content: '30 件损坏原因初步判定为入库搬运碰撞，已拍照记录，等待客户决定处置方式', createdAt: '2026-06-24T07:30:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '盘点完成，发现库存异常，等待客户审批', actor: 'Warehouse Ops', toStatus: 'PendingApproval', timestamp: '2026-06-24T07:00:00Z' },
    ],
    scenarioData: {
      skuId: 'FW-SKU-A',
      skuName: 'Fashionwave Classic Tee — Mixed Colors',
      systemQty: 1000,
      physicalQty: 970,
      variance: -30,
      countDate: '2026-06-24',
      countedBy: 'Alice M. (Inbound Lead)',
    } as import('../types/workItem').CycleCountData,
    recommendedActions: [
      { id: 'r1', label: '申请货物拍照', description: '查看 30 件损坏的实际照片', icon: 'Camera', serviceId: 'photo-request', variant: 'primary' },
      { id: 'r2', label: '申请 SKU 检查', description: '专业质检员评估损坏程度', icon: 'Search', serviceId: 'sku-inspection', variant: 'secondary' },
      { id: 'r3', label: '申请翻修', description: '轻度损坏可翻修后重新上架', icon: 'Tool', serviceId: 'rework-service', variant: 'secondary' },
      { id: 'r4', label: '申请处置销毁', description: '严重损坏，合规销毁清账', icon: 'Trash2', serviceId: 'disposition-service', variant: 'warning' },
    ],
  },

  // ── 事件类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-011',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'order-stuck',
    title: '订单卡滞预警 — 120 个订单在 "分拣" 环节卡住',
    description: '系统检测到 120 个 TechCore 订单在分拣环节滞留超过 4 小时，远超正常处理时长（45 分钟）。卡滞原因：部分 SKU 库位信息缺失，分拣系统无法定位。',
    source: 'System',
    isAgentGenerated: true,
    agentName: 'Order Flow Monitor',
    createdBy: 'system',
    assignee: 'ops-team',
    owner: 'Operations Team',
    status: 'InProgress',
    priority: 'Critical',
    isPriority: true,
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-24T14:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'BATCH-240624-A',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['order-stuck', 'picking', 'urgent'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '系统检测到批量订单卡滞', actor: 'Order Flow Monitor', toStatus: 'InProgress', timestamp: '2026-06-24T09:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '申请加急处理', description: '优先解决分拣卡滞，当日恢复出库', icon: 'Zap', serviceId: 'expedite-processing', variant: 'primary' },
      { id: 'r2', label: '分批发货', description: '已完成分拣的订单先行发出', icon: 'Package', variant: 'secondary' },
      { id: 'r3', label: '优先作业通道', description: '开启专属优先通道，减少后续风险', icon: 'Star', serviceId: 'priority-handling', variant: 'secondary' },
    ],
    scenarioData: {
      orderId: 'BATCH-240624-A',
      stuckStage: '分拣 (Picking)',
      stuckReason: '部分 SKU 库位信息缺失，分拣设备无法定位货物，需手动干预',
      stuckSince: '2026-06-24T05:00:00Z',
      affectedQty: 120,
    } as import('../types/workItem').OrderStuckData,
  },

  {
    id: 'WI-012',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'order-overdue',
    title: '订单超时通知 — ORD-20260622-9901 延误 36 小时',
    description: '订单 ORD-20260622-9901 已超出承诺发货 SLA 36 小时。承诺发货时间：6月23日 18:00，实际未发出。原因：承运商取件延误。请确认是否需要更换承运商或通知终端消费者。',
    source: 'System',
    isAgentGenerated: true,
    agentName: 'SLA Monitor Agent',
    createdBy: 'system',
    assignee: 'shipping-ops',
    owner: 'Shipping Team',
    status: 'Open',
    priority: 'Critical',
    isPriority: true,
    createdAt: '2026-06-24T06:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'ORD-20260622-9901',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['overdue', 'sla-breach', 'carrier'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: 'SLA 超时自动报警', actor: 'SLA Monitor Agent', toStatus: 'Open', timestamp: '2026-06-24T06:00:00Z' },
    ],
    scenarioData: {
      orderId: 'ORD-20260622-9901',
      stuckStage: '等待承运商取件 (Carrier Pickup)',
      stuckReason: '承运商 UPS 因车辆故障未能按时取件，已延误 36 小时，备选承运商已联系',
      stuckSince: '2026-06-22T18:00:00Z',
      affectedQty: 1,
    } as import('../types/workItem').OrderStuckData,
  },

  {
    id: 'WI-013',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'address-exception',
    title: '地址异常 — 18 个订单收货地址无法识别',
    description: '系统检测到 18 个 Fashionwave 订单的收货地址无法被承运商系统识别，可能导致无法配送。请及时核实并更新地址信息，避免退件和二次发货费用。',
    source: 'System',
    isAgentGenerated: true,
    agentName: 'Address Validator Agent',
    createdBy: 'system',
    assignee: 'fashionwave-portal',
    owner: 'Shipping Team',
    status: 'Open',
    priority: 'High',
    isPriority: true,
    createdAt: '2026-06-24T08:30:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-24T18:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'BATCH-ADDR-001',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['address', 'exception', 'shipping'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '地址验证失败，自动暂停相关订单发货', actor: 'Address Validator Agent', toStatus: 'Open', timestamp: '2026-06-24T08:30:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '改派正确地址', description: '仓库收到新地址后立即更新发货', icon: 'MapPin', serviceId: 'redirect-shipment', variant: 'primary' },
      { id: 'r2', label: '暂停此批订单', description: '等待地址确认后再统一处理', icon: 'Pause', serviceId: 'hold-shipment', variant: 'secondary' },
    ],
  },

  {
    id: 'WI-014',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'inventory-threshold',
    title: '库存低于安全阈值 — SKU TCORE-CABLE 仅剩 48 件',
    description: 'TechCore SKU TCORE-CABLE 当前可用库存 48 件，已低于您设定的安全库存阈值（50 件）。建议安排补货，避免因库存不足导致订单无法及时处理。',
    source: 'System',
    isAgentGenerated: true,
    agentName: 'Inventory Monitor Agent',
    createdBy: 'system',
    assignee: 'techcore-portal',
    owner: 'Inventory Team',
    status: 'Open',
    priority: 'Medium',
    createdAt: '2026-06-24T07:00:00Z',
    updatedAt: '2026-06-24T07:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-CABLE',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['low-stock', 'replenishment', 'threshold'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '库存低于阈值，自动触发补货提醒', actor: 'Inventory Monitor Agent', toStatus: 'Open', timestamp: '2026-06-24T07:00:00Z' },
    ],
    scenarioData: {
      skuId: 'TCORE-CABLE',
      systemReceived: 48,
      available: 48,
      damaged: 0,
    } as import('../types/workItem').InventoryAnomalyData,
  },

  {
    id: 'WI-015',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'order-sla-risk',
    title: 'SLA 风险预警 — 35 个订单 4 小时内可能超时',
    description: '系统预测 35 个 TechCore 订单将在 4 小时内达到 SLA 截止时间，当前处理进度落后于预期。如不立即干预，预计约 20 个订单会超时发货，影响您的客户体验评分。',
    source: 'Agent',
    isAgentGenerated: true,
    agentName: 'SLA Predictor Agent',
    createdBy: 'system',
    assignee: 'ops-team',
    owner: 'Operations Team',
    status: 'Open',
    priority: 'High',
    createdAt: '2026-06-24T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-06-24T14:00:00Z',
    relatedObjectType: 'Order',
    relatedObjectId: 'BATCH-SLA-240624',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['sla-risk', 'prediction', 'urgent'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: 'AI 预测 SLA 风险，发出预警', actor: 'SLA Predictor Agent', toStatus: 'Open', timestamp: '2026-06-24T10:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '申请加急处理', description: '对高风险订单优先处理', icon: 'Zap', serviceId: 'expedite-processing', variant: 'primary' },
      { id: 'r2', label: '接受延误风险', description: '确认已知悉，不采取额外操作', icon: 'Check', variant: 'secondary' },
    ],
  },

  {
    id: 'WI-016',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'shipment-delayed',
    title: '运输延误通知 — SHP-20260622-0055 承运商延误 2 天',
    description: 'FedEx 通知包裹 SHP-20260622-0055 因极端天气在中转枢纽延误，预计额外延误 2 个工作日。终端消费者尚未收到通知，请决定是否主动告知。',
    source: 'System',
    isAgentGenerated: false,
    createdBy: 'fedex-webhook',
    assignee: 'fashionwave-portal',
    owner: 'Shipping Team',
    status: 'Open',
    priority: 'Medium',
    createdAt: '2026-06-24T08:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
    relatedObjectType: 'Shipment',
    relatedObjectId: 'SHP-20260622-0055',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['shipping-delay', 'weather', 'fedex'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: 'FedEx 延误通知接入，自动创建工单', actor: 'System', toStatus: 'Open', timestamp: '2026-06-24T08:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '通知终端消费者', description: '发送延误说明邮件，主动管理预期', icon: 'Mail', variant: 'primary' },
      { id: 'r2', label: '升级快递服务', description: '更换更快的承运商缩短延误', icon: 'Truck', serviceId: 'upgrade-shipping', variant: 'secondary' },
      { id: 'r3', label: '无需操作', description: '确认已知悉，等待正常配送完成', icon: 'Check', variant: 'secondary' },
    ],
  },

  {
    id: 'WI-017',
    type: 'Alert',
    driver: 'EventDriven',
    scenario: 'receiving-completed',
    title: '收货完成通知 — PO-20260624-201 到货 2,400 件',
    description: '采购订单 PO-20260624-201 已完成收货入库，实收 2,400 件，数量与 PO 一致，货物状态良好。所有 SKU 已完成扫码上架，可立即出库。',
    source: 'System',
    isAgentGenerated: false,
    createdBy: 'inbound-system',
    assignee: 'fashionwave-portal',
    owner: 'Inbound Team',
    status: 'Resolved',
    priority: 'Low',
    createdAt: '2026-06-24T10:30:00Z',
    updatedAt: '2026-06-24T10:30:00Z',
    relatedObjectType: 'PO',
    relatedObjectId: 'PO-20260624-201',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: false,
    tags: ['receiving', 'po-complete', 'notification'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '收货完成，自动通知客户', actor: 'Inbound System', toStatus: 'Resolved', timestamp: '2026-06-24T10:30:00Z' },
    ],
    scenarioData: {
      poId: 'PO-20260624-201',
      poQty: 2400,
      receivedQty: 2400,
      variance: 0,
      skuId: 'FW-2024-SUMMER',
      skuName: 'Fashionwave Summer Collection',
      receivedDate: '2026-06-24',
    } as import('../types/workItem').ReceivingDiscrepancyData,
  },

  // ── 计划类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-018',
    type: 'Task',
    driver: 'PlanningDriven',
    scenario: 'inbound-forecast',
    title: '到货预报 — 下周到货 20,000 件，请确认收货容量',
    description: 'TechCore 预计下周（6月30日-7月4日）将有三批货物到达，合计约 20,000 件。仓库需提前安排收货人员和仓位，请确认到货计划以便提前备货。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'inbound-team',
    owner: 'Inbound Team',
    status: 'Open',
    priority: 'Medium',
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    slaDeadline: '2026-06-27T17:00:00Z',
    relatedObjectType: 'PO',
    relatedObjectId: 'FORECAST-W27',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: false,
    tags: ['inbound-forecast', 'capacity', 'planning'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '客户提交到货预报', actor: 'TechCore Portal', toStatus: 'Open', timestamp: '2026-06-24T09:00:00Z' },
    ],
    scenarioData: {
      eventName: '7月第一周常规到货',
      eventType: 'inbound',
      expectedQty: 20000,
      targetDate: '2026-06-30',
      skus: ['TCORE-X100', 'TCORE-CABLE', 'TCORE-HUB-PRO'],
      prepItems: [
        '安排额外收货人员（预计需要 6 名）',
        '提前预留 B 区 200 个托盘位',
        '准备收货标签打印机 × 3',
        '通知质检团队配合验货',
      ],
    } as import('../types/workItem').ForecastData,
  },

  {
    id: 'WI-019',
    type: 'Task',
    driver: 'PlanningDriven',
    scenario: 'promotion-forecast',
    title: 'Prime Day 备货计划 — 7月11-12日，预计出库量 × 5',
    description: 'Prime Day 促销活动将于 7月11-12日举行，Fashionwave 预计出库量为日常的 5 倍，约 15,000 件/天。仓库需提前扩容并安排弹性人员，请确认备货和产能计划。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'fashionwave-portal',
    assignee: 'ops-mgr',
    owner: 'Operations Team',
    status: 'InProgress',
    priority: 'High',
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    slaDeadline: '2026-07-08T17:00:00Z',
    relatedObjectType: 'Campaign',
    relatedObjectId: 'PRIME-DAY-2026',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: true,
    estimatedFee: 8500,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['prime-day', 'promotion', 'capacity'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '促销备货计划提交', actor: 'Fashionwave Portal', toStatus: 'Open', timestamp: '2026-06-15T10:00:00Z' },
      { id: 'a2', action: '仓库确认初步产能方案', actor: 'Ops Manager', fromStatus: 'Open', toStatus: 'InProgress', timestamp: '2026-06-20T14:00:00Z' },
    ],
    scenarioData: {
      eventName: 'Amazon Prime Day 2026',
      eventType: 'promotion',
      expectedQty: 30000,
      targetDate: '2026-07-11',
      skus: ['FW-DENIM-002', 'FW-2024-BLK', 'FW-2024-RED'],
      prepItems: [
        '临时扩容 500 个托盘位（C 区）',
        '安排弹性人员 12 名（7月8-13日）',
        '与 FedEx、UPS 协商增加取件频次',
        '提前完成所有 Kitting 服务（5,000 套）',
        '确认包材充足（预计消耗 30,000 个纸箱）',
      ],
    } as import('../types/workItem').ForecastData,
  },

  {
    id: 'WI-020',
    type: 'Task',
    driver: 'PlanningDriven',
    scenario: 'launch-event',
    title: '新品发布准备 — TechCore Pro Hub 2.0 7月1日上架',
    description: 'TechCore 将于 7月1日发布 Pro Hub 2.0 系列新品，仓库需要提前准备：接收 3,000 件新品入库、完成标签贴附、准备专属包材（定制礼盒 + 填充物），并配置独立库位。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'ops-team',
    owner: 'Operations Team',
    status: 'InProgress',
    priority: 'High',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    slaDeadline: '2026-06-30T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-HUB-PRO2',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 2200,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['launch', 'new-sku', 'preparation'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '新品发布计划提交', actor: 'TechCore Portal', toStatus: 'Open', timestamp: '2026-06-10T10:00:00Z' },
      { id: 'a2', action: '仓库开始准备工作', actor: 'Ops Team', fromStatus: 'Open', toStatus: 'InProgress', timestamp: '2026-06-15T09:00:00Z' },
    ],
    scenarioData: {
      eventName: 'TechCore Pro Hub 2.0 发布',
      eventType: 'launch',
      expectedQty: 3000,
      targetDate: '2026-07-01',
      skus: ['TCORE-HUB-PRO2'],
      prepItems: [
        '确认新品贴标规范（已收到标签文件）',
        '采购定制礼盒 3,000 个（已下单，6月28日到货）',
        '配置独立库区 A-15（100 平米）',
        '完成系统 SKU 初始化设置',
        '安排发布当日专属打包团队',
      ],
    } as import('../types/workItem').ForecastData,
  },

  // ── 协同类 ──────────────────────────────────────────────────────────────────

  {
    id: 'WI-021',
    type: 'Project',
    driver: 'CollaborationDriven',
    scenario: 'new-sku-launch',
    title: '新 SKU 上架项目 — FW-2026-WINTER 系列（6 款）',
    description: 'Fashionwave 与仓库联合推进 2026 冬季新品上架项目，涉及 6 个 SKU、标签设计确认、纸箱规格审批、主包装确认及存储要求设定。预计 7月15日完成全部上架准备。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'fashionwave-portal',
    assignee: 'project-mgr',
    owner: 'Strategic Accounts',
    status: 'InProgress',
    priority: 'High',
    createdAt: '2026-06-18T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-07-15T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'FW-2026-WINTER',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: true,
    estimatedFee: 1800,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['new-sku', 'winter', 'project', 'fashionwave'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'Janet (Fashionwave)', role: 'Customer', content: '标签文件已发送，请确认规格是否符合仓库打印要求', createdAt: '2026-06-20T10:00:00Z', isInternal: false },
      { id: 'c2', author: 'Tom (WH Project)', role: 'Warehouse', content: '标签规格已确认，打印测试通过。纸箱规格请提供详细尺寸', createdAt: '2026-06-21T14:00:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '项目启动', actor: 'Janet (Fashionwave)', toStatus: 'Open', timestamp: '2026-06-18T10:00:00Z' },
      { id: 'a2', action: '标签规格确认完成', actor: 'Tom (WH Project)', fromStatus: 'Open', toStatus: 'InProgress', timestamp: '2026-06-21T14:00:00Z' },
    ],
    scenarioData: {
      projectType: 'new-sku-launch',
      currentStepId: 'carton-spec',
      targetDate: '2026-07-15',
      materials: ['标签文件 × 6', '纸箱规格表', '主包装样品', '存储条件说明'],
      steps: [
        { id: 'label', step: 1, title: '标签规格确认', description: '客户提供标签文件，仓库验证打印规格', status: 'done', actor: 'Joint', completedAt: '2026-06-21', notes: '6款标签全部通过测试' },
        { id: 'carton-spec', step: 2, title: '纸箱规格审批', description: '客户提供纸箱尺寸重量，仓库确认堆叠存储方式', status: 'active', actor: 'Customer', notes: '等待客户提供详细尺寸规格' },
        { id: 'master-pack', step: 3, title: '主包装确认', description: '确认每箱装量、包装方式和防护材料', status: 'pending', actor: 'Joint' },
        { id: 'storage', step: 4, title: '存储要求设定', description: '配置库位类型、温湿度要求、堆叠限制', status: 'pending', actor: 'Warehouse' },
        { id: 'golive', step: 5, title: '上架准备完成', description: '系统初始化，库位分配，首批收货就绪', status: 'pending', actor: 'Warehouse' },
      ],
    } as import('../types/workItem').ProjectData,
  },

  {
    id: 'WI-022',
    type: 'Project',
    driver: 'CollaborationDriven',
    scenario: 'packaging-change',
    title: '包装变更项目 — TechCore Hub X100 外箱更新',
    description: 'TechCore 申请更新 Hub X100 外箱设计（新品牌 VI 升级），需要仓库对现有库存约 800 件进行重新包装。流程：样品确认 → 客户审批 → 批量翻包 → 完成。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'techcore-portal',
    assignee: 'project-mgr',
    owner: 'Value-Add Services',
    status: 'PendingApproval',
    priority: 'Medium',
    createdAt: '2026-06-19T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-07-05T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'TCORE-X100',
    warehouseCode: 'WH-001',
    customerCode: 'TECHCORE',
    isChargeable: true,
    estimatedFee: 960,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['packaging-change', 'repackaging', 'project'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'WH Project Team', role: 'Warehouse', content: '样品翻包已完成，请查看附件中的样品照片并确认是否符合要求', createdAt: '2026-06-23T14:00:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '包装变更项目启动', actor: 'TechCore Portal', toStatus: 'Open', timestamp: '2026-06-19T10:00:00Z' },
      { id: 'a2', action: '样品制作完成，等待客户审批', actor: 'WH Project Team', fromStatus: 'InProgress', toStatus: 'PendingApproval', timestamp: '2026-06-23T14:00:00Z' },
    ],
    scenarioData: {
      projectType: 'packaging-change',
      currentStepId: 'approval',
      targetDate: '2026-07-05',
      materials: ['新版包装设计稿', '样品照片', '工时报价单'],
      steps: [
        { id: 'request', step: 1, title: '变更申请提交', description: '客户说明包装变更要求和设计规格', status: 'done', actor: 'Customer', completedAt: '2026-06-19' },
        { id: 'sample', step: 2, title: '样品制作', description: '仓库按新设计制作 3 件样品', status: 'done', actor: 'Warehouse', completedAt: '2026-06-23', notes: '样品已完成并拍照' },
        { id: 'approval', step: 3, title: '客户审批样品', description: '客户确认样品是否符合预期，批准后开始批量作业', status: 'active', actor: 'Customer', notes: '请查收样品照片，确认后我们立即开始批量' },
        { id: 'bulk', step: 4, title: '批量翻包', description: '对现有 800 件库存进行重新包装（预计 2-3 个工作日）', status: 'pending', actor: 'Warehouse' },
        { id: 'complete', step: 5, title: '完成验收', description: '客户抽验完成品，确认入库', status: 'pending', actor: 'Joint' },
      ],
    } as import('../types/workItem').ProjectData,
  },

  {
    id: 'WI-023',
    type: 'Project',
    driver: 'CollaborationDriven',
    scenario: 'warehouse-project',
    title: '全仓换标项目 — Fashionwave 品牌升级 15,000 件',
    description: 'Fashionwave 全线产品完成品牌升级，需要对仓库现有 15,000 件库存进行全量换标。项目分 3 批次执行，预计 3 周完成，期间正常出库不受影响（换标完成批次优先出库）。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'fashionwave-portal',
    assignee: 'project-mgr',
    owner: 'Value-Add Services',
    status: 'InProgress',
    priority: 'Medium',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
    slaDeadline: '2026-07-14T17:00:00Z',
    relatedObjectType: 'Customer',
    relatedObjectId: 'FASHIONWAVE',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: true,
    estimatedFee: 3750,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['relabeling', 'warehouse-project', 'bulk'],
    evidence: [],
    comments: [],
    activityLog: [
      { id: 'a1', action: '换标项目启动', actor: 'Fashionwave Portal', toStatus: 'Open', timestamp: '2026-06-10T10:00:00Z' },
      { id: 'a2', action: '第一批 5,000 件换标完成', actor: 'Project Manager', fromStatus: 'Open', toStatus: 'InProgress', timestamp: '2026-06-17T17:00:00Z' },
    ],
    scenarioData: {
      projectType: 'warehouse-project',
      currentStepId: 'batch-2',
      targetDate: '2026-07-14',
      materials: ['新版标签（已到货 15,000 张）', '标签打印机设置文件'],
      steps: [
        { id: 'batch-1', step: 1, title: '第一批换标（5,000 件）', description: 'A 区库存，包含 FW-DENIM 系列', status: 'done', actor: 'Warehouse', completedAt: '2026-06-17', notes: '完成率 100%，质检抽验通过' },
        { id: 'batch-2', step: 2, title: '第二批换标（5,000 件）', description: 'B 区库存，包含 FW-2024 系列', status: 'active', actor: 'Warehouse', notes: '进度 60%（3,000/5,000 件），预计 6月26日完成' },
        { id: 'batch-3', step: 3, title: '第三批换标（5,000 件）', description: 'C 区库存，包含 FW-2026 系列', status: 'pending', actor: 'Warehouse' },
        { id: 'qc', step: 4, title: '全量质检验收', description: '客户抽验换标质量，确认无误后关闭项目', status: 'pending', actor: 'Joint' },
      ],
    } as import('../types/workItem').ProjectData,
  },

  // ── 临时盘点请求（增值服务） ────────────────────────────────────────────────

  {
    id: 'WI-024',
    type: 'Request',
    driver: 'RequestDriven',
    scenario: 'inventory-audit-request',
    title: '临时盘点请求 — SKU FW-2024-BLK 账实核对',
    description: 'Fashionwave 发起临时盘点请求，原因：近期出库订单多次反馈数量与预期不符，怀疑 SKU FW-2024-BLK 存在库存偏差。希望仓库尽快安排人工盘点并出具差异报告。',
    source: 'Customer',
    isAgentGenerated: false,
    createdBy: 'fashionwave-portal',
    assignee: 'warehouse-ops',
    owner: 'Warehouse Ops',
    status: 'Open',
    priority: 'Medium',
    isPriority: false,
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-06-25T09:00:00Z',
    slaDeadline: '2026-06-27T17:00:00Z',
    relatedObjectType: 'SKU',
    relatedObjectId: 'FW-2024-BLK',
    warehouseCode: 'WH-001',
    customerCode: 'FASHIONWAVE',
    isChargeable: true,
    estimatedFee: 120,
    currency: 'USD',
    billingStatus: 'Pending',
    tags: ['inventory-audit', 'cycle-count', 'vas'],
    evidence: [],
    comments: [
      { id: 'c1', author: 'Sarah (Fashionwave)', role: 'Customer', content: '近一周有 3 个订单反馈收到的数量比下单少 1-2 件，麻烦帮忙核实下库存准确性', createdAt: '2026-06-25T09:10:00Z', isInternal: false },
    ],
    activityLog: [
      { id: 'a1', action: '客户发起临时盘点请求', actor: 'Fashionwave Portal', toStatus: 'Open', timestamp: '2026-06-25T09:00:00Z' },
    ],
    recommendedActions: [
      { id: 'r1', label: '安排专项盘点', description: '仓库对该 SKU 进行人工全量盘点', icon: 'ClipboardList', serviceId: 'inventory-audit-service', variant: 'primary' },
      { id: 'r2', label: '拍照确认库存', description: '先拍照确认库位货物状态', icon: 'Camera', serviceId: 'photo-request', variant: 'secondary' },
    ],
    scenarioData: {
      skuId: 'FW-2024-BLK',
      systemReceived: 620,
      available: 620,
      damaged: 0,
    } as import('../types/workItem').InventoryAnomalyData,
  },
]

// ─── Context interface ────────────────────────────────────────────────────────

interface CollaborationContextValue {
  items: WorkItem[]
  getItemById: (id: string) => WorkItem | undefined
  updateStatus: (id: string, status: WorkItemStatus, note?: string) => void
  addComment: (id: string, comment: Omit<WorkItemComment, 'id'>) => void
  addEvidence: (id: string, evidence: Omit<WorkItemEvidence, 'id'>) => void
  getUnreadCount: () => number
  purchasedServices: Set<string>
  purchaseService: (serviceId: string) => void
}

const CollaborationContext = createContext<CollaborationContextValue | null>(null)

export function CollaborationProvider({ children }: { children: ReactNode }) {
  const [items, setItems] = useState<WorkItem[]>(SEED_ITEMS)
  const [purchasedServices, setPurchasedServices] = useState<Set<string>>(
    new Set(['photo-request', 'relabeling', 'kitting', 'expedite-processing', 'inventory-audit-service'])
  )

  const getItemById = useCallback(
    (id: string) => items.find((item) => item.id === id),
    [items]
  )

  const updateStatus = useCallback(
    (id: string, status: WorkItemStatus, note?: string) => {
      setItems((prev) =>
        prev.map((item) => {
          if (item.id !== id) return item
          return {
            ...item,
            status,
            updatedAt: new Date().toISOString(),
            activityLog: [
              ...item.activityLog,
              {
                id: `a${Date.now()}`,
                action: `Status changed to ${status}`,
                actor: 'Current User',
                fromStatus: item.status,
                toStatus: status,
                timestamp: new Date().toISOString(),
                note,
              },
            ],
          }
        })
      )
    },
    []
  )

  const addComment = useCallback(
    (id: string, comment: Omit<WorkItemComment, 'id'>) => {
      setItems((prev) =>
        prev.map((item) => {
          if (item.id !== id) return item
          return {
            ...item,
            updatedAt: new Date().toISOString(),
            comments: [...item.comments, { ...comment, id: `c${Date.now()}` }],
          }
        })
      )
    },
    []
  )

  const addEvidence = useCallback(
    (id: string, evidence: Omit<WorkItemEvidence, 'id'>) => {
      setItems((prev) =>
        prev.map((item) => {
          if (item.id !== id) return item
          return {
            ...item,
            updatedAt: new Date().toISOString(),
            evidence: [
              ...item.evidence,
              { ...evidence, id: `ev${Date.now()}` },
            ],
            activityLog: [
              ...item.activityLog,
              {
                id: `a${Date.now()}`,
                action: `Evidence uploaded: ${evidence.label}`,
                actor: evidence.uploadedBy,
                toStatus: item.status,
                timestamp: new Date().toISOString(),
              },
            ],
          }
        })
      )
    },
    []
  )

  const getUnreadCount = useCallback(
    () => items.filter((i) => i.type === 'Request' && (i.status === 'Open' || i.status === 'InProgress' || i.status === 'PendingApproval')).length,
    [items]
  )

  const purchaseService = useCallback((serviceId: string) => {
    setPurchasedServices((prev) => new Set([...prev, serviceId]))
  }, [])

  return (
    <CollaborationContext.Provider
      value={{ items, getItemById, updateStatus, addComment, addEvidence, getUnreadCount, purchasedServices, purchaseService }}
    >
      {children}
    </CollaborationContext.Provider>
  )
}

export function useCollaboration() {
  const ctx = useContext(CollaborationContext)
  if (!ctx) throw new Error('useCollaboration must be used within CollaborationProvider')
  return ctx
}
